name: Born In The 80s Productions
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Born In The 80s Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f4c8f0'
    - '#fe6eef'
    - '#ca0394'
    - '#8e2b74'
  brandStrength: 0.5
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
