name: Born In The 80s Productions
favicon: null
layout_spectrum: 0.06884916
typography_spectrum: 0.2678024
title: Born In The 80s Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.1984688
  lightness: 0.2899999
  saturation: 0.8902707
  rhythmicContrast: 0.7956836
purpose: []
