layout_spectrum: 0.06884916
typography_spectrum: 0.2678024
color:
  saturation: 0.8902707
  lightness: 0.2899999
  brandStrength: 0.1984688
  rhythmicContrast: 0.7956836
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
name: Born In The 80s Productions
